name: DSmartTrader Test
on:
  pull_request:
    branches:
      - master
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Node
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e
        with:
          node-version: 18.x
      - name: Install dependencies
        uses: "./.github/actions/npm_install"
      - name: Build
        uses: "./.github/actions/build"
        with:
          target: production
          rudderstackKey:  vars.RUDDERSTACK_KEY
          growthbookDecryptionKey: secrets.GROWTHBOOK_DECRYPTION_KEY
          growthbookClientKey: vars.GROWTHBOOK_CLIENT_KEY
      - name: "Run Tests"
        run: npm run test
